commands:
  - name: add
    description: "Add package to requirements.txt"
    type: bash
  - name: pull
    description: "git module init && pull"
    type: bash
  - name: reset
    description: "Remove venv and setup"
    type: bash
  - name: setup
    description: "Runs a shell script to set up the Python virtual environment and install the requirements."
    type: bash
  - name: python
    description: "[py] run python"
    type: python
  - name: age
    description: "Check the age of the directory if there is a .git"
    type: bash

  # - name: extract
  #   description: "[py] Extract something"
  #   type: python

  # - name: new
  #   description: "Create new item"
  #   type: bash

#run custom scripts using cli run <name>
scripts:
  - something: something
